/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.molina.emails;

import org.junit.Test;
import static org.junit.Assert.*;

public class EmailTest {
  private static String PATH_TO_CONFIG = "src/main/resources/email_config.ini";
  private static String TO = "neomol@protonmail.com";
  private static String SUBJECT = "prueba";
  private static String CONTENT = ":D";
  private static Email testEmail;

  @Test
  public void testBuildingEmail() {
    EmailBuilder builder = new EmailBuilder();
    Email email = builder.build(PATH_TO_CONFIG);

    assertFalse(email == null);

    testEmail = email;
  }

  @Test
  public void testSendingEmail() {
    assertFalse(testEmail == null);
    assertTrue(testEmail.sendEmail(TO, SUBJECT, CONTENT));
  }
}
