/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.molina.emails;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
  @Test
  public void testSomeLibraryMethod() {
    // Library classUnderTest = new Library();
    // assertTrue("someLibraryMethod should return 'true'",
				// classUnderTest.someLibraryMethod());
		Library classUnderTest = Library.LibraryFactory("../../email_config.ini");
  }
}
