/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.molina.emails;

import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;

public class Library {
  public boolean someLibraryMethod() {
    // Recipient's email ID needs to be mentioned.
    String to = "neomol@protonmail.com";

    // Sender's email ID needs to be mentioned
    String from = "Reinaldo Molina <rmolin88@gmail.com>";

    // Get system properties
    Properties properties = System.getProperties();
    System.out.println("About to configure application....");

    // Setup mail server
    properties.setProperty("mail.smtp.auth", "true");
    properties.setProperty("mail.smtp.starttls.enable", "true");
    properties.setProperty("mail.smtp.host", "smtp.gmail.com");
    properties.setProperty("mail.smtp.port", "465");
    properties.setProperty("mail.smtp.socketFactory.port", "465");
    properties.setProperty("mail.smtp.socketFactory.class",
                           "javax.net.ssl.SSLSocketFactory");

    // Get the default Session object.
    Session session = Session.getDefaultInstance(properties,
    new javax.mail.Authenticator() {
      protected PasswordAuthentication getPasswordAuthentication() {
        return new PasswordAuthentication(
                 "user", "password");// Specify the Username and the PassWord
      }
    });

    System.out.println("Set properties. Let the fun begin....");
    try {
      // Create a default MimeMessage object.
      MimeMessage message = new MimeMessage(session);

      // Set From: header field of the header.
      message.setFrom(new InternetAddress(from));

      // Set To: header field of the header.
      message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));

      // Set Subject: header field
      message.setSubject("This is the Subject Line!");

      // Now set the actual message
      message.setText("This is actual message");

      // Send message
      Transport.send(message);
      System.out.println("Sent message successfully....");
      return true;
    } catch (MessagingException mex) {
      mex.printStackTrace();
      return false;
    }
  }
}
