/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.molina.emails;

import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;

public class Library {
    public boolean someLibraryMethod() {
			// Recipient's email ID needs to be mentioned.
			String to = "neomol@protonmail.com";

			// Sender's email ID needs to be mentioned
			String from = "rmolin88@gmail.com";

			// Assuming you are sending email from localhost
			String host = "smtps://$my_username@smtp.gmail.com:465/";

			// Get system properties
			Properties properties = System.getProperties();

			// Setup mail server
			// properties.setProperty("mail.smtp.host", host);
			properties.setProperty("mail.smtp.auth", "true");
			properties.setProperty("mail.smtp.starttls.enable", "true");
			properties.setProperty("mail.smtp.host", "smtp.gmail.com");
			properties.setProperty("mail.smtp.port", "587");
			properties.setProperty("mail.user", "rmolin88");
			properties.setProperty("mail.password", "gzheilsrpvgrcold");

			// Get the default Session object.
			Session session = Session.getDefaultInstance(properties);

			try {
				// Create a default MimeMessage object.
				MimeMessage message = new MimeMessage(session);

				// Set From: header field of the header.
				message.setFrom(new InternetAddress(from));

				// Set To: header field of the header.
				message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));

				// Set Subject: header field
				message.setSubject("This is the Subject Line!");

				// Now set the actual message
				message.setText("This is actual message");

				// Send message
				Transport.send(message);
				System.out.println("Sent message successfully....");
				return true;
			} catch (MessagingException mex) {
				mex.printStackTrace();
				return false;
			}
    }
}
